service: s3-serverless-service

plugins:
  - serverless-step-functions

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: Admin
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
            - "s3:GetObject"
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - Ref: ServerlessDeploymentBucket
                - "/*"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - Ref: ServerlessDeploymentBucket
                - "/*"

functions:
  resizer:
    handler: handler.resizer
    events:
      - s3:
          bucket: chiru-learning-s3-lambda-integration
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads
            - suffix: .jpg
