service: serverless-service-new
plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: Admin
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s2:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::chiru-serverless-service-learning-008/*"
    - Effect: "Allow"
      Action:
        - "states:ListStateMachines"
        - "states:StartExecution"
      Resource: "arn:aws:states:*:*:*"

functions:
  resizeImage:
    handler: handler.resizeImage
  executeStepFunction:
    handler: handler.executeStepFunction
    events:
      - s3:
          bucket: chiru-serverless-service-learning-008
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads
            - suffix: .jpg
  thumbnails:
    handler: handler.thumbnails
    events:
      - s3:
          bucket: chiru-serverless-service-learning-008
          event: s3:ObjectCreated:*
          rules:
            - prefix: resized-uploads
            - suffix: .jpg
  saveImageMetaData:
    handler: handler.saveImageMetaData
stepFunctions:
  # validate: true
  stateMachines:
    imageProcessingMachine:
      definition:
        Comment: "image processing state machine"
        StartAt: Parallel
        States:
          Parallel:
            Type: Parallel
            Next: FinalState
            Branches:
              - StartAt: ResizeImage
                States:
                  ResizeImage:
                    Type: Task
                    Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-resizeImage"
                    End: true
              - StartAt: SaveImageMetaData
                States:
                  SaveImageMetaData:
                    Type: Task
                    Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-saveImageMetaData"
                    End: true
          FinalState:
            Type: Pass
            End: true
