AWSTemplateFormatVersion: "2010-09-09"
Description: "Roles for EC2 instances"

Resources:
  # A role so that ECS Nodes can work with other AWS Services
  EcsNode:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EcsNode
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"

      Path: "/"
      ManagedPolicyArns:
        # attach the Elastic Container Service policy that will allow instance
        # to communicate with EC2 Service and also holds CloudLog Permissions
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"

  EcsNodeProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      InstanceProfileName: EcsNode
      Roles:
        - !Ref EcsNode

  #Role so that Instance can find and attach the volume to itself
  EcsVolumeAccess:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EcsVolumeAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"

      Path: "/"
      Policies:
        - PolicyName: "AllowEC2InstanceToManageVolume"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:*Volume*"
                  - "ec2:CreateSnapshot"
                  - "ec2:DescribeSnapshot"
                Resource: "*"

              - Effect: Deny
                Action:
                  - "ec2:DeleteVolume"
                Resource: "*"

  EcsVolumeAccessProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EcsVolumeAccess
      Path: "/"
      Roles:
        - !Ref EcsVolumeAccess
